services:
  db:
    build:
      context: ./ToDoListDB
      dockerfile: Dockerfile
    container_name: oracle-db
    ports:
        - "1521:1521"
    environment:
       ORACLE_PASSWORD: "oracle"
    healthcheck:
      test: [ "CMD-SHELL", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - oracle_data:/opt/oracle/oradata

  backend:
    build:
     context: ./ToDoList/demo
     dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 1521
      DB_SERVICE: FREEPDB1
      DB_USERNAME: ETHAN
      DB_PASSWORD: Ethan9901
      DB_URL: jdbc:oracle:thin:@//db:1521/FREEPDB1

volumes:
  oracle_data:


